import sys, asyncio
import os

if sys.platform.startswith("win"):
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
from typing import Annotated
from fastmcp import FastMCP
from dotenv import load_dotenv
from pg_age_helper import PGAgeHelper





load_dotenv()

mcp = FastMCP("Graph Age MCP Server")

GRAPH_NAME = os.getenv("GRAPH_NAME", "")
_ONTOLOGY_MEMORY: dict[str, str] = {}


@mcp.tool
async def save_ontology(
    ontology: Annotated[str, "Generated ontology content to store in memory"],
    graph_name: Annotated[str | None, "Graph name for ontology cache key"] = None,
) -> dict:
    """
    Save the generated ontology in process memory.
    Args:
        ontology: The ontology content as text.
    Returns:
        Status indicating ontology was saved.
    """
    graph_key = (graph_name or GRAPH_NAME or "default").strip()
    _ONTOLOGY_MEMORY[graph_key] = ontology

    print("Ontology saved in memory for graph:", graph_key, "length:", len(ontology))
    return {
        "status": "saved",
        "has_ontology": True,
        "graph_name": graph_key,
        "length": len(ontology),
    }


@mcp.tool
async def fetch_ontology(
    graph_name: Annotated[str | None, "Graph name for ontology cache lookup"] = None,
) -> dict:
    """
    Fetch the ontology previously saved in process memory.
    Returns:
        The saved ontology content, if any.
    """
    graph_key = (graph_name or GRAPH_NAME or "default").strip()
    ontology = _ONTOLOGY_MEMORY.get(graph_key)
    print("Fetching ontology from memory for graph:", graph_key, "has ontology:", ontology is not None)
    return {
        "has_ontology": ontology is not None,
        "graph_name": graph_key,
        "ontology": ontology,
    }

@mcp.tool
async def query_using_sql_cypher(
    sql_query: Annotated[str, "SQL Query"],
    graph_name: Annotated[str, "Graph name to use for ag_catalog.cypher(...)"]
) -> list[dict]:
    """
    Execute the sql statement against a PostgreSQL database with the AGE extension.
    The sql query is generated by another agent. This tool simply executes the query and returns the result.
    Args:
        sql_query: The SQL query to execute.
        graph_name: Graph name to use when executing AGE cypher calls.
    Returns:
        The query result as a list of dictionaries.
    """
    rows = await pg_helper.query_using_sql_cypher(sql_query, graph_name)
    print("Query executed, result:\n", rows)
    return rows





if __name__ == "__main__":
    global pg_helper
    pg_helper = asyncio.run(PGAgeHelper.create())

    #test_query = """SELECT *
    #    FROM ag_catalog.cypher('customer_graph', $$
#
    #    MATCH (c:Customer)
    #    WHERE c.payload.name = 'Customer 002'
    #    OPTIONAL MATCH (c)-[:ADOPTED_PRODUCT]->(p:Product)
    #    RETURN c.payload.name AS customer_name, collect(DISTINCT p.payload.name) AS product_names
#
    #    $$) AS (
    #    customer_name ag_catalog.agtype,
    #    product_names ag_catalog.agtype
    #    );"""
    #
    #result = asyncio.run(query_using_sql_cypher(test_query))
    #print("Test query result:\n", result)

    mcp.run(transport="streamable-http", host="0.0.0.0", port=3002)