import sys, asyncio

if sys.platform.startswith("win"):
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
from typing import Annotated
from fastmcp import FastMCP
from dotenv import load_dotenv
from pg_age_helper import PGAgeHelper





load_dotenv()

mcp = FastMCP("Graph Age MCP Server")

@mcp.tool
async def query_using_sql_cypher(sql_query: Annotated[str, "SQL Query"]) -> list[dict]:
    """
    Execute the sql statement against a PostgreSQL database with the AGE extension.
    The sql query is generated by another agent. This tool simply executes the query and returns the result.
    Args:
        sql_query: The SQL query to execute.
    Returns:
        The query result as a list of dictionaries.
    """
    rows = await pg_helper.query_using_sql_cypher(sql_query)
    print("Query executed, result:\n", rows)
    return rows





if __name__ == "__main__":
    global pg_helper
    pg_helper = asyncio.run(PGAgeHelper.create())

    #test_query = """SELECT *
    #    FROM ag_catalog.cypher('customer_graph', $$
#
    #    MATCH (c:Customer)
    #    WHERE c.payload.name = 'Customer 002'
    #    OPTIONAL MATCH (c)-[:ADOPTED_PRODUCT]->(p:Product)
    #    RETURN c.payload.name AS customer_name, collect(DISTINCT p.payload.name) AS product_names
#
    #    $$) AS (
    #    customer_name ag_catalog.agtype,
    #    product_names ag_catalog.agtype
    #    );"""
    #
    #result = asyncio.run(query_using_sql_cypher(test_query))
    #print("Test query result:\n", result)

    mcp.run(transport="streamable-http", port=3002)