CREATE INDEX IF NOT EXISTS idx_about_area_id ON "customer_graph"."ABOUT_AREA" (id);
CREATE INDEX IF NOT EXISTS idx_about_area_start_id ON "customer_graph"."ABOUT_AREA" (start_id);
CREATE INDEX IF NOT EXISTS idx_about_area_end_id ON "customer_graph"."ABOUT_AREA" (end_id);
CREATE INDEX IF NOT EXISTS idx_about_area_props_gin ON "customer_graph"."ABOUT_AREA" USING GIN (((properties::text)::jsonb));
CREATE INDEX IF NOT EXISTS idx_about_area_payload_gin ON "customer_graph"."ABOUT_AREA" USING GIN ((((properties::text)::jsonb -> 'payload')));
CREATE INDEX IF NOT EXISTS idx_about_area_payload_name_lower ON "customer_graph"."ABOUT_AREA" (lower((((properties::text)::jsonb -> 'payload' ->> 'name'))));
CREATE INDEX IF NOT EXISTS idx_adopted_feature_id ON "customer_graph"."ADOPTED_FEATURE" (id);
CREATE INDEX IF NOT EXISTS idx_adopted_feature_start_id ON "customer_graph"."ADOPTED_FEATURE" (start_id);
CREATE INDEX IF NOT EXISTS idx_adopted_feature_end_id ON "customer_graph"."ADOPTED_FEATURE" (end_id);
CREATE INDEX IF NOT EXISTS idx_adopted_feature_props_gin ON "customer_graph"."ADOPTED_FEATURE" USING GIN (((properties::text)::jsonb));
CREATE INDEX IF NOT EXISTS idx_adopted_feature_payload_gin ON "customer_graph"."ADOPTED_FEATURE" USING GIN ((((properties::text)::jsonb -> 'payload')));
CREATE INDEX IF NOT EXISTS idx_adopted_feature_payload_name_lower ON "customer_graph"."ADOPTED_FEATURE" (lower((((properties::text)::jsonb -> 'payload' ->> 'name'))));
CREATE INDEX IF NOT EXISTS idx_adopted_product_id ON "customer_graph"."ADOPTED_PRODUCT" (id);
CREATE INDEX IF NOT EXISTS idx_adopted_product_start_id ON "customer_graph"."ADOPTED_PRODUCT" (start_id);
CREATE INDEX IF NOT EXISTS idx_adopted_product_end_id ON "customer_graph"."ADOPTED_PRODUCT" (end_id);
CREATE INDEX IF NOT EXISTS idx_adopted_product_props_gin ON "customer_graph"."ADOPTED_PRODUCT" USING GIN (((properties::text)::jsonb));
CREATE INDEX IF NOT EXISTS idx_adopted_product_payload_gin ON "customer_graph"."ADOPTED_PRODUCT" USING GIN ((((properties::text)::jsonb -> 'payload')));
CREATE INDEX IF NOT EXISTS idx_adopted_product_payload_name_lower ON "customer_graph"."ADOPTED_PRODUCT" (lower((((properties::text)::jsonb -> 'payload' ->> 'name'))));
CREATE INDEX IF NOT EXISTS idx_communication_id ON "customer_graph"."Communication" (id);
CREATE INDEX IF NOT EXISTS idx_communication_props_gin ON "customer_graph"."Communication" USING GIN (((properties::text)::jsonb));
CREATE INDEX IF NOT EXISTS idx_communication_payload_gin ON "customer_graph"."Communication" USING GIN ((((properties::text)::jsonb -> 'payload')));
CREATE INDEX IF NOT EXISTS idx_communication_payload_name_lower ON "customer_graph"."Communication" (lower((((properties::text)::jsonb -> 'payload' ->> 'name'))));
CREATE INDEX IF NOT EXISTS idx_contract_id ON "customer_graph"."Contract" (id);
CREATE INDEX IF NOT EXISTS idx_contract_props_gin ON "customer_graph"."Contract" USING GIN (((properties::text)::jsonb));
CREATE INDEX IF NOT EXISTS idx_contract_payload_gin ON "customer_graph"."Contract" USING GIN ((((properties::text)::jsonb -> 'payload')));
CREATE INDEX IF NOT EXISTS idx_contract_payload_name_lower ON "customer_graph"."Contract" (lower((((properties::text)::jsonb -> 'payload' ->> 'name'))));
CREATE INDEX IF NOT EXISTS idx_customer_id ON "customer_graph"."Customer" (id);
CREATE INDEX IF NOT EXISTS idx_customer_props_gin ON "customer_graph"."Customer" USING GIN (((properties::text)::jsonb));
CREATE INDEX IF NOT EXISTS idx_customer_payload_gin ON "customer_graph"."Customer" USING GIN ((((properties::text)::jsonb -> 'payload')));
CREATE INDEX IF NOT EXISTS idx_customer_payload_name_lower ON "customer_graph"."Customer" (lower((((properties::text)::jsonb -> 'payload' ->> 'name'))));
CREATE INDEX IF NOT EXISTS idx_for_product_id ON "customer_graph"."FOR_PRODUCT" (id);
CREATE INDEX IF NOT EXISTS idx_for_product_start_id ON "customer_graph"."FOR_PRODUCT" (start_id);
CREATE INDEX IF NOT EXISTS idx_for_product_end_id ON "customer_graph"."FOR_PRODUCT" (end_id);
CREATE INDEX IF NOT EXISTS idx_for_product_props_gin ON "customer_graph"."FOR_PRODUCT" USING GIN (((properties::text)::jsonb));
CREATE INDEX IF NOT EXISTS idx_for_product_payload_gin ON "customer_graph"."FOR_PRODUCT" USING GIN ((((properties::text)::jsonb -> 'payload')));
CREATE INDEX IF NOT EXISTS idx_for_product_payload_name_lower ON "customer_graph"."FOR_PRODUCT" (lower((((properties::text)::jsonb -> 'payload' ->> 'name'))));
CREATE INDEX IF NOT EXISTS idx_feature_id ON "customer_graph"."Feature" (id);
CREATE INDEX IF NOT EXISTS idx_feature_props_gin ON "customer_graph"."Feature" USING GIN (((properties::text)::jsonb));
CREATE INDEX IF NOT EXISTS idx_feature_payload_gin ON "customer_graph"."Feature" USING GIN ((((properties::text)::jsonb -> 'payload')));
CREATE INDEX IF NOT EXISTS idx_feature_payload_name_lower ON "customer_graph"."Feature" (lower((((properties::text)::jsonb -> 'payload' ->> 'name'))));
CREATE INDEX IF NOT EXISTS idx_had_comm_id ON "customer_graph"."HAD_COMM" (id);
CREATE INDEX IF NOT EXISTS idx_had_comm_start_id ON "customer_graph"."HAD_COMM" (start_id);
CREATE INDEX IF NOT EXISTS idx_had_comm_end_id ON "customer_graph"."HAD_COMM" (end_id);
CREATE INDEX IF NOT EXISTS idx_had_comm_props_gin ON "customer_graph"."HAD_COMM" USING GIN (((properties::text)::jsonb));
CREATE INDEX IF NOT EXISTS idx_had_comm_payload_gin ON "customer_graph"."HAD_COMM" USING GIN ((((properties::text)::jsonb -> 'payload')));
CREATE INDEX IF NOT EXISTS idx_had_comm_payload_name_lower ON "customer_graph"."HAD_COMM" (lower((((properties::text)::jsonb -> 'payload' ->> 'name'))));
CREATE INDEX IF NOT EXISTS idx_has_contract_id ON "customer_graph"."HAS_CONTRACT" (id);
CREATE INDEX IF NOT EXISTS idx_has_contract_start_id ON "customer_graph"."HAS_CONTRACT" (start_id);
CREATE INDEX IF NOT EXISTS idx_has_contract_end_id ON "customer_graph"."HAS_CONTRACT" (end_id);
CREATE INDEX IF NOT EXISTS idx_has_contract_props_gin ON "customer_graph"."HAS_CONTRACT" USING GIN (((properties::text)::jsonb));
CREATE INDEX IF NOT EXISTS idx_has_contract_payload_gin ON "customer_graph"."HAS_CONTRACT" USING GIN ((((properties::text)::jsonb -> 'payload')));
CREATE INDEX IF NOT EXISTS idx_has_contract_payload_name_lower ON "customer_graph"."HAS_CONTRACT" (lower((((properties::text)::jsonb -> 'payload' ->> 'name'))));
CREATE INDEX IF NOT EXISTS idx_has_opportunity_id ON "customer_graph"."HAS_OPPORTUNITY" (id);
CREATE INDEX IF NOT EXISTS idx_has_opportunity_start_id ON "customer_graph"."HAS_OPPORTUNITY" (start_id);
CREATE INDEX IF NOT EXISTS idx_has_opportunity_end_id ON "customer_graph"."HAS_OPPORTUNITY" (end_id);
CREATE INDEX IF NOT EXISTS idx_has_opportunity_props_gin ON "customer_graph"."HAS_OPPORTUNITY" USING GIN (((properties::text)::jsonb));
CREATE INDEX IF NOT EXISTS idx_has_opportunity_payload_gin ON "customer_graph"."HAS_OPPORTUNITY" USING GIN ((((properties::text)::jsonb -> 'payload')));
CREATE INDEX IF NOT EXISTS idx_has_opportunity_payload_name_lower ON "customer_graph"."HAS_OPPORTUNITY" (lower((((properties::text)::jsonb -> 'payload' ->> 'name'))));
CREATE INDEX IF NOT EXISTS idx_has_qbr_id ON "customer_graph"."HAS_QBR" (id);
CREATE INDEX IF NOT EXISTS idx_has_qbr_start_id ON "customer_graph"."HAS_QBR" (start_id);
CREATE INDEX IF NOT EXISTS idx_has_qbr_end_id ON "customer_graph"."HAS_QBR" (end_id);
CREATE INDEX IF NOT EXISTS idx_has_qbr_props_gin ON "customer_graph"."HAS_QBR" USING GIN (((properties::text)::jsonb));
CREATE INDEX IF NOT EXISTS idx_has_qbr_payload_gin ON "customer_graph"."HAS_QBR" USING GIN ((((properties::text)::jsonb -> 'payload')));
CREATE INDEX IF NOT EXISTS idx_has_qbr_payload_name_lower ON "customer_graph"."HAS_QBR" (lower((((properties::text)::jsonb -> 'payload' ->> 'name'))));
CREATE INDEX IF NOT EXISTS idx_has_telemetry_id ON "customer_graph"."HAS_TELEMETRY" (id);
CREATE INDEX IF NOT EXISTS idx_has_telemetry_start_id ON "customer_graph"."HAS_TELEMETRY" (start_id);
CREATE INDEX IF NOT EXISTS idx_has_telemetry_end_id ON "customer_graph"."HAS_TELEMETRY" (end_id);
CREATE INDEX IF NOT EXISTS idx_has_telemetry_props_gin ON "customer_graph"."HAS_TELEMETRY" USING GIN (((properties::text)::jsonb));
CREATE INDEX IF NOT EXISTS idx_has_telemetry_payload_gin ON "customer_graph"."HAS_TELEMETRY" USING GIN ((((properties::text)::jsonb -> 'payload')));
CREATE INDEX IF NOT EXISTS idx_has_telemetry_payload_name_lower ON "customer_graph"."HAS_TELEMETRY" (lower((((properties::text)::jsonb -> 'payload' ->> 'name'))));
CREATE INDEX IF NOT EXISTS idx_opportunity_id ON "customer_graph"."Opportunity" (id);
CREATE INDEX IF NOT EXISTS idx_opportunity_props_gin ON "customer_graph"."Opportunity" USING GIN (((properties::text)::jsonb));
CREATE INDEX IF NOT EXISTS idx_opportunity_payload_gin ON "customer_graph"."Opportunity" USING GIN ((((properties::text)::jsonb -> 'payload')));
CREATE INDEX IF NOT EXISTS idx_opportunity_payload_name_lower ON "customer_graph"."Opportunity" (lower((((properties::text)::jsonb -> 'payload' ->> 'name'))));
CREATE INDEX IF NOT EXISTS idx_product_id ON "customer_graph"."Product" (id);
CREATE INDEX IF NOT EXISTS idx_product_props_gin ON "customer_graph"."Product" USING GIN (((properties::text)::jsonb));
CREATE INDEX IF NOT EXISTS idx_product_payload_gin ON "customer_graph"."Product" USING GIN ((((properties::text)::jsonb -> 'payload')));
CREATE INDEX IF NOT EXISTS idx_product_payload_name_lower ON "customer_graph"."Product" (lower((((properties::text)::jsonb -> 'payload' ->> 'name'))));
CREATE INDEX IF NOT EXISTS idx_qbrartifact_id ON "customer_graph"."QBRArtifact" (id);
CREATE INDEX IF NOT EXISTS idx_qbrartifact_props_gin ON "customer_graph"."QBRArtifact" USING GIN (((properties::text)::jsonb));
CREATE INDEX IF NOT EXISTS idx_qbrartifact_payload_gin ON "customer_graph"."QBRArtifact" USING GIN ((((properties::text)::jsonb -> 'payload')));
CREATE INDEX IF NOT EXISTS idx_qbrartifact_payload_name_lower ON "customer_graph"."QBRArtifact" (lower((((properties::text)::jsonb -> 'payload' ->> 'name'))));
CREATE INDEX IF NOT EXISTS idx_raised_case_id ON "customer_graph"."RAISED_CASE" (id);
CREATE INDEX IF NOT EXISTS idx_raised_case_start_id ON "customer_graph"."RAISED_CASE" (start_id);
CREATE INDEX IF NOT EXISTS idx_raised_case_end_id ON "customer_graph"."RAISED_CASE" (end_id);
CREATE INDEX IF NOT EXISTS idx_raised_case_props_gin ON "customer_graph"."RAISED_CASE" USING GIN (((properties::text)::jsonb));
CREATE INDEX IF NOT EXISTS idx_raised_case_payload_gin ON "customer_graph"."RAISED_CASE" USING GIN ((((properties::text)::jsonb -> 'payload')));
CREATE INDEX IF NOT EXISTS idx_raised_case_payload_name_lower ON "customer_graph"."RAISED_CASE" (lower((((properties::text)::jsonb -> 'payload' ->> 'name'))));
CREATE INDEX IF NOT EXISTS idx_supportcase_id ON "customer_graph"."SupportCase" (id);
CREATE INDEX IF NOT EXISTS idx_supportcase_props_gin ON "customer_graph"."SupportCase" USING GIN (((properties::text)::jsonb));
CREATE INDEX IF NOT EXISTS idx_supportcase_payload_gin ON "customer_graph"."SupportCase" USING GIN ((((properties::text)::jsonb -> 'payload')));
CREATE INDEX IF NOT EXISTS idx_supportcase_payload_name_lower ON "customer_graph"."SupportCase" (lower((((properties::text)::jsonb -> 'payload' ->> 'name'))));
CREATE INDEX IF NOT EXISTS idx_telemetrymonth_id ON "customer_graph"."TelemetryMonth" (id);
CREATE INDEX IF NOT EXISTS idx_telemetrymonth_props_gin ON "customer_graph"."TelemetryMonth" USING GIN (((properties::text)::jsonb));
CREATE INDEX IF NOT EXISTS idx_telemetrymonth_payload_gin ON "customer_graph"."TelemetryMonth" USING GIN ((((properties::text)::jsonb -> 'payload')));
CREATE INDEX IF NOT EXISTS idx_telemetrymonth_payload_name_lower ON "customer_graph"."TelemetryMonth" (lower((((properties::text)::jsonb -> 'payload' ->> 'name'))));
CREATE INDEX IF NOT EXISTS idx__ag_label_edge_id ON "customer_graph"."_ag_label_edge" (id);
CREATE INDEX IF NOT EXISTS idx__ag_label_edge_start_id ON "customer_graph"."_ag_label_edge" (start_id);
CREATE INDEX IF NOT EXISTS idx__ag_label_edge_end_id ON "customer_graph"."_ag_label_edge" (end_id);
CREATE INDEX IF NOT EXISTS idx__ag_label_edge_props_gin ON "customer_graph"."_ag_label_edge" USING GIN (((properties::text)::jsonb));
CREATE INDEX IF NOT EXISTS idx__ag_label_edge_payload_gin ON "customer_graph"."_ag_label_edge" USING GIN ((((properties::text)::jsonb -> 'payload')));
CREATE INDEX IF NOT EXISTS idx__ag_label_edge_payload_name_lower ON "customer_graph"."_ag_label_edge" (lower((((properties::text)::jsonb -> 'payload' ->> 'name'))));
CREATE INDEX IF NOT EXISTS idx__ag_label_vertex_id ON "customer_graph"."_ag_label_vertex" (id);
CREATE INDEX IF NOT EXISTS idx__ag_label_vertex_props_gin ON "customer_graph"."_ag_label_vertex" USING GIN (((properties::text)::jsonb));
CREATE INDEX IF NOT EXISTS idx__ag_label_vertex_payload_gin ON "customer_graph"."_ag_label_vertex" USING GIN ((((properties::text)::jsonb -> 'payload')));
CREATE INDEX IF NOT EXISTS idx__ag_label_vertex_payload_name_lower ON "customer_graph"."_ag_label_vertex" (lower((((properties::text)::jsonb -> 'payload' ->> 'name'))));
